### ISSUE TITLE
未知指令 jpm

### ISSUE THREAD

**Issue by YouXam** [iTXTech/mirai-js#1]
在 mirai-console 中键入 jpm 时,  显示

```
11:16:03 [INFO] [Command] 未知指令 jpm
```

我使用的是[mirai-console-wrapper](https://github.com/mamoe/mirai-console-wrapper/releases) 的 Latest release

是否需要安装插件?

**Comment by PeratX** [comment]
需要安装本插件到`plugins`文件夹
可使用`install`命令安装

**Comment by YouXam** [comment]
我以为插件名称是jpm....
建议在文档中写清楚

**Comment by lovezm** [comment]
还有插件下载地址吗

**Comment by PeratX** [comment]
有的吧，过下就上传

**Comment by lovezm** [comment]
谢谢！
