### ISSUE TITLE
请问如果要实现@成员，或者获取图片，该怎么操作呢？

### ISSUE THREAD

**Issue by DearVa** [iTXTech/mirai-js#3]

**Comment by PeratX** [comment]
```javascript
let group = bot.groups.getOrNull(群号)
let member = group.getOrNull(QQ号)

group.sendMessage(new PlainText("你好").plus(new At(member)))
```
代码未经测试，请查看

**Comment by DearVa** [comment]
非常感谢，我这就去试试。

**Comment by DearVa** [comment]
请问有时间可不可以写一个简单的API，描述一下诸如Group、At这类对象呢？非常感谢！您的js插件对我非常有帮助！

**Comment by PeratX** [comment]
有空我写个复杂点的插件 ❤️

**Comment by PeratX** [comment]
> 请问有时间可不可以写一个简单的API，描述一下诸如Group、At这类对象呢？非常感谢！您的js插件对我非常有帮助！

Group At都是kotlin中的对象，JavaScript是直接调用mirai的类和方法的，具体可以查看kotlin文件，扩展函数有相关调用方式，而内联函数就得手写一遍了

**Comment by DearVa** [comment]
请问这里的QQ号是int型吗？因为我以前没有接触过kotlin，所以使用了您开发的js插件。

**Comment by PeratX** [comment]
抱歉代码有误，修正如下：
```javascript
let group = bots.get.groups.getOrNull(群号)
let member = group.getOrNull(QQ号)

group.sendMessage(new PlainText("你好").plus(new At(member)))
```

**Comment by PeratX** [comment]
js中没有int，直接数字就行了
kotlin中群号 QQ号都对应为`Long`

**Comment by DearVa** [comment]
非常感谢，这段代码可以使用。请问要发送图片是不是`new Image(url)`呢？
另外，`core.subscribeAlways`中都有那些事件呢？您说这里其实和mriai中的类和方法一样，可不可以告诉我mriai的api在哪里呢？我没有找到……
非常感谢！

**Comment by DearVa** [comment]
嗷，我找到了：https://github.com/mamoe/mirai/blob/master/docs/mirai.md

**Comment by DearVa** [comment]
您好，请问您对发送语音这一块的功能有没有研究呢？

**Comment by PeratX** [comment]
> 您好，请问您对发送语音这一块的功能有没有研究呢？

这个比较复杂，大概是以下流程，语音文件支持 `silk`, `amr` 格式

```javascript
importPackage(java.io)

let stream = new FileInputStream(new File(语音文件))
let group = bots.get.groups.getOrNull(群号)

let voice = group.uploadVoice(stream)

group.sendMessage(voice)
```

**Comment by DearVa** [comment]
非常感谢，我去尝试一下

**Comment by DearVa** [comment]
Cannot find function uploadVoice in object Group.
是因为我的mirai版本太低了吗，我用的是MiraiOK一键包。

**Comment by PeratX** [comment]
请等待支持1.2.0的`mirai-js`发布，这个是`mirai 1.2.0`引入的新api

**Comment by DearVa** [comment]
您好，请问您的样例中使用协程来实现的功能，与js中setInterval或者setTimeout有什么区别呢？后者也可以使用吗？

**Comment by PeratX** [comment]
> 您好，请问您的样例中使用协程来实现的功能，与js中setInterval或者setTimeout有什么区别呢？后者也可以使用吗？

`mirai-js`中的协程功能就是用来替代`setInterval`和`setTimeout`的

**Comment by PeratX** [comment]
顺便，头像大爱

**Comment by DearVa** [comment]
嗷！最爱哈娜了呜呜呜

**Comment by DearVa** [comment]
我看到您提交了适配1.2.0的源码，请问会不会发布对应的release包呢？我似乎无法在本地进行build……

**Comment by PeratX** [comment]
> 我看到您提交了适配1.2.0的源码，请问会不会发布对应的release包呢？我似乎无法在本地进行build……

今天有空發個新版本

**Comment by DearVa** [comment]
非常感谢！

**Comment by PeratX** [comment]
看了一下`mirai console`那边的API暂时无法满足`mirai-js`的需求，所以会延后两天等那边发新版

**Comment by DearVa** [comment]
辛苦了(・▽・〃)

**Comment by DearVa** [comment]
对了，请问支不支持import其他的js文件呢？

**Comment by PeratX** [comment]
这个暂时不支持，以后可能会引入类似webpack打包的方式，可以多文件编写，发行的时候编译到单文件

**Comment by DearVa** [comment]
明白了，非常感谢。

**Comment by DearVa** [comment]
刚才在尝试给朋友发送图片时，出现了图片无法显示的问题。代码如下：
```JavaScript
// f为Friend对象
let file = '文件名',
     stream = new FileInputStream(new File(file)),
     image = f.uploadImage(stream);
f.sendMessage(image);
```

**Comment by PeratX** [comment]
请给出控制台日志

**Comment by DearVa** [comment]
控制台没有出现异常。
 22:53:24 [INFO] [NETWORK] Send: OnlinePush.RespPush
 22:53:24 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 22:53:24 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
 22:53:24 [INFO] [BOT 3044611926] Dear.Va(1328886154) -> [mirai:source:30677,-667915118]喵
 22:53:24 [INFO] [NETWORK] Send: LongConn.OffPicUp
 22:53:24 [INFO] [NETWORK] Recv: RequireUpload(resourceId=/18446744072459196246-2979157892-0D99F087D35EBDE73949A15873C327F4, serverIp=[2067398326, 1474846833, -1421044101, 1593048989], serverPort=[443, 8080, 80, 443], uKey=[-9, 43, 34, -50, -34, 33, -39, 97, 36, -58, -112, -100, -52, 30, -41, 106, -114, 124, 115, 42, 28, -58, 35, 122, 63, -110, -23, 121, -53, -2, -33, -38, -96, -14, -80, -50, -9, -75, 47, -56, -3, -103, 96, 104, -10, -57, -123, -95, -113, 41, -117, -122, -122, 54, -125, 40, -36, 123, -51, -102, -79, 7, -39, 100, -100, -5, 113, -12, 61, 31, 87, -27, -120, -48, 56, -126, -4, 125, -65, 115, -43, 37, 66, 35, -47, 42, 77, 106, -54, -4, -15, 85, 103, 44, -30, 52, -90, -62, 12, 78, -60, -69, -43, -59, -110, 104, 127, -49, -119, 79, 19, 100, 61, 70, 81, -9, -104, 53, 66, 4, -122, 54, 29, 119, 56, 72, -55, -78, 38, -22, 25, -50, -125, -94, 114, -2, -5, -64, 5, -117, -64, 63, 112, 124, -70, -118, -58, -41, 60, -31, 81, 27, 55, -59, -32, -100, -24, -99, 99, -25, -24, -125, 24, -46, -47, 87, -46, 47, 116, -82, -47, -47, -104, 62, 108, 16, 104, -37, 90, 104, -21, 47, 70, -1, 35, 34, -46, -23, 12, -110, -52, 25, 19, 96, 35, 8, 1, 47, 103, 41, -91, -71, -15, 71, 64, -46, -76, -70, -23, -14, 50, -26, -110, 100, 91, -26, 11, 81, -70, -112, 10, 73, 115, 117, 34, -118, -92, -51, -43, 65, -114, -107, -127, 29, 30, -48, -103, -111, -76, -51, 26, 59, -27, -41, 9, -124, 123, 86, 60, 84, 122, 73, -61, -76, -12, -16, -76, -93, -12, -11, -123, 0, 96, -51, 58, 109, 102, -56, 29, 61, -106, 50, -24, 68, 3, -51, -53, -108, -29, 27, -26, -8, 4, 48, -47, 104, 98, 63, -29, -96, -83, 120, 8, -45, -51, -86, 76, -63, 7, 6, -95, 84, 39, 48, 69, -15, -47, 122, 5, -28, 94, 109, 78, -37, -106, 108, 44, 68, 102, 65, -47, 81, -17, -74, -118, -30, -38, -97, -74, 96, -23, 26, 67, -5, 52, -81])
 22:53:24 [INFO] [NETWORK] [Http] Uploading friend image, size=46.86 KiB
 22:53:25 [INFO] [NETWORK] [Http] Uploading friend image: succeed at 201 KiB/s
 22:53:25 [INFO] [MiraiJs] [Bot] [mirai:image:/18446744072459196246-2979157892-0D99F087D35EBDE73949A15873C327F4]
 22:53:25 [INFO] [NETWORK] Send: MessageSvc.PbSendMsg
 22:53:25 [INFO] [NETWORK] Recv: MessageSvcPbSendMsg.Response.SUCCESS
 22:53:25 [INFO] [BOT 3044611926] Friend(1328886154) <- [mirai:image:/18446744072459196246-2979157892-0D99F087D35EBDE73949A15873C327F4]
 22:53:30 [INFO] [NETWORK] Send: OnlinePush.RespPush
 22:53:31 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 22:53:31 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg

**Comment by PeratX** [comment]
这就说明，图片已经上传并发送了，图片是裂了还是压根收不到
如果没收到可以考虑账号被风控了。

**Comment by DearVa** [comment]
图裂了……图片为正常的jpg格式。

**Comment by PeratX** [comment]
建议对图片进行随即修改尝试

**Comment by DearVa** [comment]
我备用了五张jpg图片和一张png，都裂了QAQ

**Comment by DearVa** [comment]
请问http支不支持post方法提交JSON呢？
我采用OKHTTP的方法，可是有些用不了。

**Comment by PeratX** [comment]
> 请问http支不支持post方法提交JSON呢？
> 我采用OKHTTP的方法，可是有些用不了。

贴一下代码出来

**Comment by PeratX** [comment]
刚下守望

**Comment by DearVa** [comment]
OKHTTP的代码参考是这样：
```
public static final MediaType JSON
    = MediaType.get("application/json; charset=utf-8");

OkHttpClient client = new OkHttpClient();

String post(String url, String json) throws IOException {
  RequestBody body = RequestBody.create(json, JSON);
  Request request = new Request.Builder()
      .url(url)
      .post(body)
      .build();
  try (Response response = client.newCall(request).execute()) {
    return response.body().string();
  }
}
```
我就仿照写成了这样：
```
let body = http.createRequestBody(json, JSON);
    let request = http.newRequest.Builder()
      .url(url)
      .post(body)
      .build();
    let response = client.newCall(request).execute()
    return response.body().string();
```
结果像`createRequestBody`这样的方法是找不到的。
准备回归ow？qwq

**Comment by PeratX** [comment]
这个我白天写好给你吧，mirai-js对于`okhttp`的映射只有一部分，`requestBody`可能需要手动import，比如`okhttp.RequestBody.createRequestBody`

**Comment by DearVa** [comment]
好哒，我先研究研究，早点睡叭，晚安~

**Comment by PeratX** [comment]
嗯呢 晚安
有时间学习一下kotlin看看示例插件很快就入门了

**Comment by DearVa** [comment]
真的特别喜欢你的项目，我可以给你一点小小的赞助吗？

**Comment by PeratX** [comment]
> 真的特别喜欢你的项目，我可以给你一点小小的赞助吗？

可以的哦，见[FlashMaster About](https://fm.peratx.net/#/about)

新版本预计和`mirai console 1.0-M3`同步发布

**Comment by PeratX** [comment]
MiraiJs 已发布 `1.1.0-rc.1`，支持`mirai core 1.2.2`和`mirai console 1.0-M3`
语音应该也能发了，注意要`silk`或`amr`格式
[Releases](https://github.com/iTXTech/mirai-js/releases)

**Comment by DearVa** [comment]
小小的赞助了一笔qwq
这个版本的插件不支持MiraiOK，我现在需要自己build最新的Mirai-console(M3版本)，请问是不是该通过gradle来打包呢？我对gradle和kotlin的了解还不多，也没有装idle。

**Comment by DearVa** [comment]
尝试用了一下gradle jar，结果build出来一个不到1MB的mieai-console.jar...

**Comment by DearVa** [comment]
实在是build不出来mirai-console-pure-1.0-M3……

**Comment by PeratX** [comment]
要运行`shadowJar`
直接下载
https://github.com/project-mirai/mirai-repo/raw/master/shadow/mirai-console-pure/mirai-console-pure-1.0-M3-all.jar
https://github.com/project-mirai/mirai-repo/raw/master/shadow/mirai-console/mirai-console-1.0-M3-all.jar

就怕你不会启动。。。目前没有启动器可用，需要自己修改或者打命令行

**Comment by PeratX** [comment]
> 小小的赞助了一笔qwq
> 这个版本的插件不支持MiraiOK，我现在需要自己build最新的Mirai-console(M3版本)，请问是不是该通过gradle来打包呢？我对gradle和kotlin的了解还不多，也没有装idle。

收到啦，谢谢（跑去买一点点喝

**Comment by DearVa** [comment]
确实，使用该版本，miraiOK会报出异常

**Comment by PeratX** [comment]
`java -cp ".\mirai-console-1.0-M3-all.jar;mirai-console-pure-1.0-M3-all.jar;mirai-core-qqandroid-1.2.2.jar" net.mamoe.mirai.console.pure.MiraiConsolePureLoader`

三个文件都需要

https://github.com/project-mirai/mirai-repo/raw/master/shadow/mirai-core-qqandroid/mirai-core-qqandroid-1.2.2.jar

**Comment by DearVa** [comment]
非常感谢，发送语音功能已经可以使用。

**Comment by PeratX** [comment]
> 非常感谢，发送语音功能已经可以使用。

好的

**Comment by DearVa** [comment]
其实使用纯命令行还更方便，不用考虑跨平台的问题。
目前我还有两个问题，第一是关于http的请求，诸如POST之类，第二是对于接受到的图像或者语音，有没有什么办法可以存在本地呢？
望解答，感谢！

**Comment by PeratX** [comment]
> 其实使用纯命令行还更方便，不用考虑跨平台的问题。
> 目前我还有两个问题，第一是关于http的请求，诸如POST之类，第二是对于接受到的图像或者语音，有没有什么办法可以存在本地呢？
> 望解答，感谢！

这两天有空写这两个example出来

**Comment by DearVa** [comment]
请问方便的话能不能加个联系方式呀qwq？

**Comment by DearVa** [comment]
关于裂图的问题，好像是对图片格式有要求。我在QQ上下载下来的图片给机器人发就可以，但是我试了很多本机图片都不行。

**Comment by PeratX** [comment]
> 请问方便的话能不能加个联系方式呀qwq？

邮箱就是QQ

**Comment by DearVa** [comment]
再请教一个问题qwq
我用`http.get(url)`得到一个MP3文件，请问该如何储存在本地以备发送呢？储存应该调用stor的方法吧

**Comment by DearVa** [comment]
mirai可以发送文件吗，我刚去看了API好像没有这个功能？

**Comment by PeratX** [comment]
> 再请教一个问题qwq
> 我用`http.get(url)`得到一个MP3文件，请问该如何储存在本地以备发送呢？储存应该调用stor的方法吧

mirai 不支持发送文件。

mp3不能发送哦，必须是silk或者amr格式的

我会做一个把stream保存到文件的便捷方法，现在需要手动拷贝stream

**Comment by DearVa** [comment]
居然不支持发送文件呀……

**Comment by DearVa** [comment]
理论上有没有自己修改mirai源码来实现发送文件的可能性呢？

**Comment by PeratX** [comment]
> 理论上有没有自己修改mirai源码来实现发送文件的可能性呢？

有的，你把这个协议抓到了就行

**Comment by DearVa** [comment]
在最新版本中进群事件`MemberJoinEvent.Invite`和`MemberJoinEvent.Active`好像不会触发了？请问是因为API出现了改动吗？

**Comment by DearVa** [comment]
好像确实存在进群事件无法触发的bug

**Comment by PeratX** [comment]
> 好像确实存在进群事件无法触发的bug

这个是core的问题哦，已经有人提出了

**Comment by DearVa** [comment]
本地flask开个服务器，用http.get来和py联动实现一些js难以实现的功能✓

**Comment by HYLZ-2019** [comment]
> > 其实使用纯命令行还更方便，不用考虑跨平台的问题。
> > 目前我还有两个问题，第一是关于http的请求，诸如POST之类，第二是对于接受到的图像或者语音，有没有什么办法可以存在本地呢？
> > 望解答，感谢！
> 
> 这两天有空写这两个example出来

您好，请问关于http的example在哪里可以看到呢？（我想让我的bot能GET服务器上其他api的数据。）

**Comment by StageGuard** [comment]
> > > 其实使用纯命令行还更方便，不用考虑跨平台的问题。
> > > 目前我还有两个问题，第一是关于http的请求，诸如POST之类，第二是对于接受到的图像或者语音，有没有什么办法可以存在本地呢？
> > > 望解答，感谢！
> > 
> > 
> > 这两天有空写这两个example出来
> 
> 您好，请问关于http的example在哪里可以看到呢？（我想让我的bot能GET服务器上其他api的数据。）

https://github.com/iTXTech/mirai-js/blob/master/src/main/kotlin/org/itxtech/miraijs/libs/OkHttpLib.kt

**Comment by HYLZ-2019** [comment]
> > > > 其实使用纯命令行还更方便，不用考虑跨平台的问题。
> > > > 目前我还有两个问题，第一是关于http的请求，诸如POST之类，第二是对于接受到的图像或者语音，有没有什么办法可以存在本地呢？
> > > > 望解答，感谢！
> > > 
> > > 
> > > 这两天有空写这两个example出来
> > 
> > 
> > 您好，请问关于http的example在哪里可以看到呢？（我想让我的bot能GET服务器上其他api的数据。）
> 
> https://github.com/iTXTech/mirai-js/blob/master/src/main/kotlin/org/itxtech/miraijs/libs/OkHttpLib.kt

不好意思，我不会kotlin，不知道这个库里的对象怎么使用，例如说要import哪些类什么的……请问可以给一个例子吗？
