### ISSUE TITLE
根据开发文档的目录结构写插件后依旧无法载入插件

### ISSUE THREAD

**Issue by yangchaohe** [iTXTech/mirai-js#9]
环境：
- mirai-console: 2.7-M1
- mirai-console-terminal: 2.7-M1
- mirai-core-all: 2.7-M1
- mirai-js: 2.0-RC-dev1

目录结构：
![image](https://user-images.githubusercontent.com/58938416/134638118-8b925bf3-0e64-415e-9100-126b63ad5cec.png)
报错：
![image](https://user-images.githubusercontent.com/58938416/134638203-07e154fa-9ecc-43f8-82a0-fdfce823976a.png)

**Comment by StageGuard** [comment]
迟到的回复，文档写错了一个地方，是 scripts 文件夹存放脚本不是 plugins ，已经更正文档
